-- UP
CREATE TABLE IF NOT EXISTS secrets (
  id INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL,
  external_id UUID NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  expires_on DATE NOT NULL,
  token TEXT NOT NULL,
  PRIMARY KEY (id)
);
-- DOWN
DROP TABLE IF EXISTS secrets CASCADE;